### ISSUE TITLE
[Suggestion] ACRE2/TFAR integration

### ISSUE THREAD

**Issue by unhappytroll** [ArmaAchilles/AresModAchillesExpansion#173] opened 2017-11-02 12:53 UTC
By which I mean ability to spawn radios from respectful mod (TFAR has at least three different storage containers with radios and radio models, except for vehicle radios), set and change vehicle radios, and enforce frequencies either globally or to some particular radio item.

**Comment by CreepPork** [comment] 2017-11-02 15:55
There is a currently implemented module in the 0.1.0 branch, #156 module.

As for spawning radios, why couldn't you just put down a Virtual Arsenal box? I see no point having a module that spawns the radios if a player still has to equip it, maybe you can shed some light on this?

When I was designing the #156 module, I looked into ACRE compatibility but it was not possible as the lack of API functions opposed to TFAR.

**Comment by unhappytroll** [comment] 2017-11-03 10:46
hmmm, did not found it in the interface, should check more.

idea was from Lcpl_liru stream, where he wanted to give a PoW player radio to check mission progress. I know what you can set freq on LR radio (and blufor SR), set it to speaker audio and drop, and it would translate radio chat. But yes, you should go to arsenal, choose the radio and so on. why just not to spawn radio and set a freq on it from Zeus interface?
And containers with radios is not in the prop list btw.

**Comment by CreepPork** [comment] 2017-11-03 14:09
It's not in the release branch (0.0.9c). It is in the 0.1.0 branch (development).

As for the first thing, giving the radio, you can just use the attribute button Arsenal and equip players a radio, it's not that difficult but it isn't reliable.

Containers of radios should be addressed to the TFAR/ACRE2 developers, we shouldn't create further dependencies on other mods.

**Comment by CreepPork** [comment] 2017-11-03 14:11
As for now, I'm closing this issue as a partial duplicate of #156.

**Closed by CreepPork** 2017-11-03 14:11 UTC
Labels: duplicate, feature request, priority/low, rejected
