### ISSUE TITLE
[Bug] Limited Arsenal does not add weapons.

### ISSUE THREAD

**Issue by unhappytroll** [ArmaAchilles/AresModAchillesExpansion#196] opened 2017-12-07 15:32 UTC
**Arma 3 Version:** `1,80` (stable)  
**CBA Version:** `3.5` (stable)  
**AresModAchillesExpansion Version:** `0.1.0` (dev + commit hash)  

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
- ACE
- RHS
- TFAR
 - ACE-RHS compatibility mods
```

**Description:**
- Limited Arsenal do not add any weapons when applied into object.
**Steps to reproduce:**
1. Enter Zeus, place object.
2. Apply limited Arsenal (BLUFOR f.e.) onto  object.
3. Check Arsenal.There is armor and stuff, but no pistols, launchers and guns.

**Where did the issue occur?**
-  Single/Hosted multi. Does not checked on dedicated.

**RPT log file:**
https://pastebin.com/WdTnk7dR

**Comment by unhappytroll** [comment] 2017-12-07 16:02
Also I should add that from all UAV terminals looks like only IDAP's has issued into Arsenal from this module, no matter the settings.

**Comment by CreepPork** [comment] 2017-12-10 12:25
I think the Arsenal modules in total need a rewrite, they're really slow.

**Comment by CreepPork** [comment] 2017-12-10 16:58
Marked as duplicate of #200.

**Closed by CreepPork** 2017-12-10 16:58 UTC
Labels: bug, duplicate, priority/medium
