### ISSUE TITLE
Supply module GUI

### ISSUE THREAD

**Issue by Victor9401** [ArmaAchilles/AresModAchillesExpansion#198] opened 2017-12-07 17:41 UTC
**Arma 3 Version:** `1.80` (stable)  
**AresModAchillesExpansion Version:** `v0.1.0 Testers build v2`

Gui opens wrongly if player hasn't spawned any LZ or RP

**Comment by CreepPork** [comment] 2017-12-07 17:42
Duplicate of #197.

**Closed by CreepPork** 2017-12-07 17:42 UTC
Labels: bug, duplicate, priority/medium
