### ISSUE TITLE
Twin-Seat CAS Custom Loadouts Only Associated with Pilot

### ISSUE THREAD

**Issue by SkullCollector** [ArmaAchilles/AresModAchillesExpansion#128] opened 2017-10-06 20:12 UTC
Tested primarily with RHS AH-6M Littlebirds and AH-64 Apaches.

When customising the weapon loadout for these birds and other twin-seaters that have a WSO, the co-pilot becomes disassociated with controlling the weapons.

For example, when giving the Apache or Littlebird AGM-114N which are meant to be laser-guided, only the pilot gets control over the missile, but cannot lock on any lasers. The co-pilot has no option to take control.

When simply spawning an Apache with Hellfires pre-equipped, everything works as intended.
When giving the RHS A-10A custom weapons, all works as intended, probably because it's a single-seater.

However, all weapons that were pre-equipped when spawning the bird act as though empty and have to be switched past to get to the custom weapons.

The same goes for the vanilla Littlebird and ACE ordnance.

**Comment by CreepPork** [comment] 2017-10-06 20:59
Hi, thanks for the report, but it's a duplicate of #116. I fixed this issue today, already on the 0.1.0 branch.

My fix will assign all new weaponry to the gunner, even if some were assigned to the driver. If a vehicle doesn't have a gunner slot (like a plane), it will assign them to the driver.

**Closed by CreepPork** 2017-10-06 20:59 UTC
Labels: duplicate, resolved

**Comment by SkullCollector** [comment] 2017-10-06 21:47
Good to know and sorry for opening a duplicate!

Cheers and keep it up.

**Comment by CreepPork** [comment] 2017-10-07 09:48
@SkullCollector No worries!
